Repository AICoE/meteor, pull requests merged in 2021-11, with the labels that each got.

#206 how-to build jbooks
  assets/screenshot_ghpages.png
  docs/_config.yml
  docs/_toc.yml
  docs/build-jupyterbooks.md
Labels: size/M, approved, lgtm

#140 feat: Use Data list instead of tiles
  src/components/Container.jsx
  src/components/Container.module.css
  src/components/Form.jsx
  src/components/Meteors.jsx
  src/components/MeteorsTitle.jsx
  src/components/Wrapped.jsx
  src/constants.ts
  src/localstorage.ts
  src/pages/index.jsx
Labels: size/L, approved, lgtm

#212 feat: Rewamp submit form UI
  package.json
  src/components/Alerts.jsx
  src/components/BranchDropdown.jsx
  src/components/Description.jsx
  src/components/Dropdown.jsx
  src/components/Form.jsx
  src/components/Form.module.css
  src/components/Layout.jsx
  src/components/Meteors.jsx
  src/components/Select.jsx
  src/components/Select.module.scss
  src/constants.ts
  src/contexts/Alerts.jsx
  src/hooks/swr.ts
  src/hooks/useDebounce.ts
  src/pages/api/meteors.ts
  src/pages/index.jsx
  src/pages/order/[uid].jsx
  src/styles.css
Labels: size/L, approved, lgtm

#214 fix: Pipeline label in dropdown
  src/components/Meteors.jsx
Labels: size/XS, approved, lgtm

#216 docs: Update readme with installation guide, replacing '3 teams' sections
  README.md
Labels: size/M, approved, lgtm

#226 fix: Launch button on detail page and make it clickable on list
  src/components/Meteors.jsx
  src/pages/order/[uid].jsx
Labels: approved, lgtm, size/S

#227 fix: TTL submit value
  src/components/Form.jsx
Labels: size/XS, approved, lgtm

#229 Add GitHub templates for bug and feature
  .github/bug_report.md
  .github/feature_request.md
Labels: size/M, approved, lgtm

#231 feat: Show persistent meteors expiration as Never
  src/components/Description.jsx
  src/components/Form.jsx
  src/pages/order/[uid].jsx
Labels: size/XS, approved, lgtm
