Repository AICoE/meteor, pull requests merged in 2021-08, with the labels that each got.

#43 feat: Simple scaffold for Meteor PoC
  .aicoe-ci.yaml
  .gitignore
  .pre-commit-config.yaml
  assets/poc.gif
  manifests/deployment.yaml
  manifests/kustomization.yaml
  manifests/rolebinding.yaml
  manifests/route.yaml
  manifests/service.yaml
  manifests/serviceaccount.yaml
  next-env.d.ts
  next.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/meteoroid.svg
  public/robots.txt
  src/components/DefaultLayout.jsx
  src/components/Description.jsx
  src/components/Fulfilment.jsx
  src/components/LogoCard.jsx
  src/components/Step.jsx
  src/constants.ts
  src/k8s.ts
  src/pages/404.jsx
  src/pages/_app.jsx
  src/pages/_document.jsx
  src/pages/api/meteor/[id].ts
  src/pages/api/meteors.ts
  src/pages/index.jsx
  src/pages/order/[uid].jsx
  src/reportWebVitals.ts
  src/styles.css
  tsconfig.json
Labels: size/XXL

#61 Add YouTube links
  README.md
Labels: approved, lgtm, size/XS

#66 feat: Add prometheus metrics to Meteor Shower
  next.config.js
  package-lock.json
  package.json
  src/metrics.ts
  src/pages/_app.jsx
  src/pages/api/meteor/[id].ts
  src/pages/api/meteors.ts
  src/pages/api/metrics.ts
Labels: size/M, approved, lgtm

#67 feat: Enable Google Analytics
  manifests/deployment.yaml
  src/constants.ts
  src/pages/_app.jsx
  src/pages/_document.jsx
  src/pages/api/metrics.ts
  src/reportWebVitals.ts
Labels: size/M, approved, lgtm

#70 typo in button
  src/pages/index.jsx
Labels: size/XS, approved, lgtm

#68 feat: Add dependabot config
  .github/dependabot.yml
Labels: approved, lgtm, size/S

#69 feat: Add hema to approvers
  OWNERS
Labels: approved, lgtm, size/S

#83 Updated flowchart
  docs/images/project-flowchart.png
Labels: size/XS

#89 refactor: Rewrite the Frontend to match RedHat UI better
  .pre-commit-config.yaml
  .vscode/launch.json
  manifests/deployment.yaml
  manifests/kustomization.yaml
  manifests/role.yaml
  manifests/rolebinding.yaml
  next.config.js
  package-lock.json
  package.json
  public/rh_logo.png
  src/components/DefaultLayout.jsx
  src/components/Description.jsx
  src/components/Footer.jsx
  src/components/Footer.module.css
  src/components/Form.jsx
  src/components/Form.module.css
  src/components/Fulfilment.jsx
  src/components/Header.jsx
  src/components/Header.module.scss
  src/components/Layout.jsx
  src/components/LogoCard.jsx
  src/components/Meteors.jsx
  src/components/NotFoundIcon.jsx
  src/components/NotFoundIcon.module.scss
  src/components/PhaseIcon.jsx
  src/components/Step.jsx
  src/components/Time.jsx
  src/components/Wrapped.jsx
  src/k8s.ts
  src/pages/404.jsx
  src/pages/api/console.ts
  src/pages/api/meteors.ts
  src/pages/index.jsx
  src/pages/order/[uid].jsx
  src/styles.css
Labels: size/XXL, approved, lgtm

#97 update front page prose
  src/pages/index.jsx
Labels: approved, lgtm, size/S

#99 Index text visual
  src/pages/index.jsx
Labels: size/M, lgtm

#100 refactor: Move SWR hooks into a separate lib
  package.json
  src/components/Description.jsx
  src/components/Meteors.jsx
  src/components/MeteorsTitle.jsx
  src/pages/index.jsx
  src/pages/order/[uid].jsx
  src/swr.ts
Labels: size/M, approved, lgtm

#104 feat: Prefetch api and show pipeline outputs
  next-env.d.ts
  src/components/Description.jsx
  src/components/Meteors.jsx
  src/pages/index.jsx
  src/pages/order/[uid].jsx
  src/swr.ts
Labels: size/M, approved, lgtm

#121 chore: Cleanup dependencies
  package-lock.json
  package.json
Labels: size/L

#120 fix: When there's no pipeline to render default to empty array
  src/pages/order/[uid].jsx
Labels: size/XS
